### ISSUE TITLE
confirm space of data and atlases

### ISSUE THREAD

**Issue by willgray** [openconnectome/ndmg#23]
We now read data with nibabel - confirm that headers and data are in a consistent (or at least not misleading to our algorithms space). 

We discovered an issue when looking at them in mipav.

**Comment by willgray** [comment]
note that trt was nearly perfect with a totally weird set of atlases, although perhaps that just means we were registering to the wrong thing consistently?

**Comment by willgray** [comment]
@gkiar - fixed?

**Comment by gkiar** [comment]
Yup, fixed using nilearn's resample. Also, atlases were re-aligned such
that the mask and parcellations overlay in both real and voxel space.

--
Greg Kiar <gkiar07@gmail.com>
